### ISSUE TITLE
[Tensorflow] ValueError: Cannot feed value of shape (1,) for Tensor 'Inputs/InputFrame:0', which has shape '(1, 257, None, 1)'

### ISSUE THREAD

**Issue by peiwenhuang27** [intel/lpot#12]
**Environment**: Google Colab, Tensorflow 2.2.0, Intel Tensorflow 2.2.0

I used a custom dataset to store the data, and used `common.dataloader` to load the dataset.
`quantizer.calib_dataloader = common.DataLoader(dataset, batch_size=1)`
Later, I input a pre-trained `pb` model for quantization, 
and the model has an input node of shape `(1, 257, None, 1)`.

Upon running the quantization, the following error occured:

>Traceback (most recent call last):
>  File "main.py", line 134, in <module>
>    evaluate_opt_graph.run()
>  File "main.py", line 116, in run
>    q_model = quantizer()
>  File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/quantization.py", line 170, in __call__
>    self.strategy.traverse()
>  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 287, in traverse
>    self.baseline = self._evaluate(self.model)
>  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 425, in _evaluate
>    val = self.objective.evaluate(eval_func, model)
>  File "/usr/local/lib/python3.7/dist-packages/lpot/objective.py", line 213, in evaluate
>    acc = eval_func(model)
>  File "/usr/local/lib/python3.7/dist-packages/lpot/utils/create_obj_from_config.py", line 127, in eval_func
>    tensorboard, fp32_baseline)
>  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tensorflow.py", line 211, in evaluate
>    predictions = model.sess.run(output_tensor, feed_dict)
>  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 958, in run
>    run_metadata_ptr)
>  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1157, in _run
>    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
>ValueError: Cannot feed value of shape (1,) for Tensor 'Inputs/InputFrame:0', which has shape '(1, 257, None, 1)'

I'm not sure why this error occurred, though I suspect it's due to the `None` dimension. 
Is there any workaround to it without having to set the `None` dimension to be fixed?  Thanks.

**Comment by ftian1** [comment]
May we know the domain the model works on? is NLP? It's rarely seen the 3rd dim is None on CV domain and need user to specify.

I think when you construct the calibration dataloader, you need specify collate_fn. It's used to concat each batch into a big mini-batch along 3rd dim. if you are not familiar with what collate_fn means, pls refer to https://pytorch.org/docs/stable/data.html

quantizer.calib_dataloader = common.DataLoader(dataset, batch_size=1, collate_fn=xxx)   # implement a collate_fn as the 3rd input of common.DataLoader().

**Comment by peiwenhuang27** [comment]
I am working with audio processing, and the 3rd dim represents the length of time.

Thank you, I did not know collate_fn can be used for this circumstance, I will look into it.

On the other hand, I tried running it with fixed 3rd dim and this part worked fine. However, I encountered another error (not related to this issue, I can submit as another issue if you want):
When evaluating FP32 tensorflow model:

> Traceback (most recent call last):
>   File "main.py", line 134, in <module>
>     evaluate_opt_graph.run()
>   File "main.py", line 118, in run
>     q_model = quantizer()
>   File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/quantization.py", line 170, in __call__
>     self.strategy.traverse()
>   File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 287, in traverse
>     self.baseline = self._evaluate(self.model)
>   File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 425, in _evaluate
>     val = self.objective.evaluate(eval_func, model)
>   File "/usr/local/lib/python3.7/dist-packages/lpot/objective.py", line 213, in evaluate
>     acc = eval_func(model)
>   File "/usr/local/lib/python3.7/dist-packages/lpot/utils/create_obj_from_config.py", line 127, in eval_func
>     tensorboard, fp32_baseline)
>   File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tensorflow.py", line 234, in evaluate
>     metric.update(predictions, labels)
>   File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/metric/metric.py", line 540, in update
>     preds, labels = _shape_validate(preds, labels)
>   File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/metric/metric.py", line 274, in _shape_validate
>     of labels {} does not match shape of predictions {}'.format(labels.shape, preds.shape)
> AttributeError: 'list' object has no attribute 'shape'

So I checked the source code, and it seems that the lines previous to the assert has made sure to convert pred and label into numpy array object. I have no idea how this came about.

`def _shape_validate(preds, labels):`
`assert type(preds) in [int, list, np.ndarray], 'preds must be in int or list, ndarray'`
`assert type(labels) in [int, list, np.ndarray], 'labels must be in int or list, ndarray'`    
`if isinstance(preds, int):`        
`preds = [np.array([preds])]`    
`elif isinstance(preds[0], int):`
`        preds = [np.array(preds)]`    
`else:`
`        preds = [np.array(pred) for pred in preds]`
`...`
`assert all([pred.shape == label.shape for (pred, label) in zip(preds, labels)]), 'shape \`
`           of labels {} does not match shape of predictions {}'.format(labels.shape, preds.shape)`
