### ISSUE TITLE
Custom dataset for multiple inputs

### ISSUE THREAD

**Issue by peiwenhuang27** [intel/lpot#19]
Hi,
I want to construct a custom dataset that is to be used by Common dataloader. My model has two inputs and one output, but I only know that from the documentation in the repo, `Dataset.getitem()` can be written in the following fashion:
```
class Dataset(object):
    def __init__(self, args):
        # init code here

    def __getitem__(self, idx):
        # use idx to get data and label
        return data, label

    def __len__(self):
        return len
```
whereas the return objects of `__getitem__()` are data, label respectively.

I tried to pass my inputs in a tuple:
```
    def __getitem__(self, idx):
        return (data0, data1), label
```

a list:
```
    def __getitem__(self, idx):
        return [data0, data1], label
```

and even a dictionary:
```
    def __getitem__(self, idx):
        return {'input0': data0, 'input1': data1}, label
```

but none of them work. What is the proper way of passing mutiple inputs in the `__getitem__` function?

Thank you.

**Comment by peiwenhuang27** [comment]
I checked the source code of ONNX adapter and found the following code in `evaluate()` function:

```
        ort_inputs = {}
        len_inputs = len(session.get_inputs())
        inputs_names = [session.get_inputs()[i].name for i in range(len_inputs)]
        for idx, batch in enumerate(dataloader):
            labels = batch[1]
            if measurer is not None:
                for i in range(len_inputs):
                    # in case dataloader contains non-array input
                    if not isinstance(batch[i], np.ndarray):
                        ort_inputs.update({inputs_names[i]: np.array(batch[i])})
                    else:
                        ort_inputs.update({inputs_names[i]: batch[i]})
                measurer.start()
                predictions = session.run(None, ort_inputs)
                measurer.end()
            else:
                for i in range(len_inputs):
                    ort_inputs.update({inputs_names[i]: batch[i]})
                predictions = session.run(None, ort_inputs)
```

I'm guessing this means that if I write my `getitem` function like this:
```
def __getitem__(self, idx):
        return data0, data1, label
```
`ort_inputs` will update my inputs as {inputs_names[0]: data0, inputs_names[1]: data1}, which is correct, while **labels are wrongly stored as it takes data1 into the variable**. I wonder if changing the line
```
labels = batch[1]
```
to 
```
labels = batch[-1]
```
will fix the error I've been encountering?

Thank you.

**Comment by ftian1** [comment]
@peiwenhuang27 thanks for raising this issue. We in fact has fixed this issue in internal and will be released soon (maybe this week)

you can try if this patch file works at your side.
[onnxrt.txt](https://github.com/intel/lpot/files/6852439/onnxrt.txt)

with this patch, you can create custom dataset like below.

tuple:
    def __getitem__(self, idx):
        return (data0, data1), label

or a list:
    def __getitem__(self, idx):
        return [data0, data1], label

**Comment by peiwenhuang27** [comment]
Having installed the package and `cd` to the folder of dist-packages containing LPOT, I was trying to apply the patch with the command:
```
!git apply onnxrt.txt
```

But it prints:
```
/content/onnxrt.txt:30: trailing whitespace.
                    'number of input tensors must align with graph inputs'  
/content/onnxrt.txt:31: trailing whitespace.
            
/content/onnxrt.txt:40: trailing whitespace.
                        ort_inputs.update({inputs_names[i]: inputs[i]})   
error: patch failed: lpot/adaptor/onnxrt.py:392
error: lpot/adaptor/onnxrt.py: patch does not apply
```

Not sure if there is something that I did it wrong? Thank you.

**Comment by ftian1** [comment]
could you pls manually merge it? this patch is generated by comparing this fix with previous commit. maybe the base file version is not exactly same with public one

**Comment by peiwenhuang27** [comment]
Thanks! I manually merged the code, and the part of evaluating FP32 model baseline seems to have run smoothly, as it prints out the accuracy and latency.
But looks like some other part in the quantization process also encounters a similar problem:

```
2021-07-21 06:09:17.159380: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-21 06:09:23 [INFO] Getting FP32 model baseline...
tcmalloc: large alloc 1073741824 bytes == 0x55ba6b310000 @  0x7f2da06f3b6b 0x7f2da0713379 0x7f2cc6a6b5fc 0x7f2cc6a70ee4 0x7f2cc6a61626 0x7f2cc6a1e3a4 0x7f2cc6a28140 0x7f2cc6d2501c 0x7f2cc6d25935 0x7f2cc6d66ef7 0x7f2cc6d8ce21 0x55b9e8db8bf8 0x55b9e8e2c6f2 0x55b9e8e26c35 0x55b9e8db973a 0x55b9e8e27d67 0x55b9e8e27235 0x55b9e8db973a 0x55b9e8e27d67 0x55b9e8e27235 0x55b9e8db973a 0x55b9e8e27b0e 0x55b9e8db965a 0x55b9e8e27d67 0x55b9e8db965a 0x55b9e8e27d67 0x55b9e8db965a 0x55b9e8e27d67 0x55b9e8db9b99 0x55b9e8dfce79 0x55b9e8db87b2
2021-07-21 06:10:51 [INFO] Save tuning history to /content/drive/My Drive/Work/model_quantization/lpot_files/onnx/lpot_workspace/2021-07-21_06-08-56/./history.snapshot
2021-07-21 06:10:51 [INFO] FP32 baseline is: [accuracy: 0.2271, duration (seconds): 87.3484]
2021-07-21 06:10:51 [ERROR] Unexpected exception RuntimeError('Could not create tensor from given input list') happened during turing!
2021-07-21 06:10:51 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit...
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    q_model.save(args.output_model)
AttributeError: 'NoneType' object has no attribute 'save'
```

**Comment by peiwenhuang27** [comment]
Hi, I looked at the source code and found out the bug was in `onnxrt_mid.py`, so I went ahead and fixed it. I have created a PR, please review if it's ok to merge. Thanks!

However, there is still another bug in my process of quantization. After I have a quantized model, in the evalutation of the model, the following shows:

```
2021-07-22 03:36:30 [INFO] Pass quantize model elapsed time: 30189.42 ms
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    q_model = quantize()
  File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/quantization.py", line 178, in __call__
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 318, in traverse
    self.last_tune_result = self._evaluate(self.last_qmodel)
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 424, in _evaluate
    val = self.objective.evaluate(eval_func, model)
  File "/usr/local/lib/python3.7/dist-packages/lpot/objective.py", line 213, in evaluate
    acc = eval_func(model)
  File "/usr/local/lib/python3.7/dist-packages/lpot/utils/create_obj_from_config.py", line 131, in eval_func
    tensorboard, fp32_baseline)
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/onnxrt.py", line 385, in evaluate
    session = ort.InferenceSession(input_graph.model.SerializeToString(), sess_options)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 228, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:fused StatefulPartitionedCall/model/1/Conv2D_quant : Unrecognized attribute: activation for operator QLinearConv
```

Should I open another issue for this? Thank you.

**Comment by ftian1** [comment]
this issue we have fixed in internal as well. could you pls wait for this weekend's v1.5.1 release?

**Comment by peiwenhuang27** [comment]
Sure! Thank you, I'll wait till the new version comes out to use it.
